Vagrant.configure("2") do |config|
    config.vm.define "web" do |web|
      web.vm.box = "ubuntu/focal64"
      web.vm.hostname = "web-server"
      web.vm.provision :shell, path: "web_script.sh"
      web.vm.network :forwarded_port, guest: 80, host: 4567
      web.vm.network "private_network", ip: "192.168.50.4"
      web.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
      end
    end
  
    config.vm.define "db" do |db|
      db.vm.box = "ubuntu/focal64"
      db.vm.hostname = "db-server"
      db.vm.provision :shell, path: "db_script.sh"
      db.vm.network "private_network", ip: "192.168.50.5"
      db.vm.provider "virtualbox" do |vb|
        vb.memory = "2048"
      end
    end
  end